"""empty message

Revision ID: 19a8ce6689f7
Revises: 99db56b604cd
Create Date: 2023-04-15 18:54:16.937335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a8ce6689f7'
down_revision = '99db56b604cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['favorites_id'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['favorites_id'], ['id'])

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['favorites_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['favorites_id'], ['id'])

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['favorites_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorites_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorites_id')

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorites_id')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorites_id')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorites_id')

    op.drop_table('favorites')
    # ### end Alembic commands ###
