"""empty message

Revision ID: 1db963587496
Revises: b73657ecf4bc
Create Date: 2023-04-15 18:42:50.465741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db963587496'
down_revision = 'b73657ecf4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('person_homeworld_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld_id')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'person', ['person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('person_homeworld_id_fkey', 'planets', ['homeworld_id'], ['id'])

    # ### end Alembic commands ###
