"""empty message

Revision ID: 99db56b604cd
Revises: 1db963587496
Create Date: 2023-04-15 18:45:48.173787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99db56b604cd'
down_revision = '1db963587496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('person_starships_id_fkey', type_='foreignkey')
        batch_op.drop_column('starships_id')

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'person', ['person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starships_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('person_starships_id_fkey', 'starships', ['starships_id'], ['id'])

    # ### end Alembic commands ###
